version: "3.9"

networks:
  prova-php-entrevista:
services:
  webserver:
    image: nginx:1.21.3-alpine
    container_name: prova-php-entrevista-webserver
    networks:
      - prova-php-entrevista
    ports:
      - ${WEBSERVER_HOST_PORT}:${WEBSERVER_DOCKER_PORT}
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - "./html:/usr/share/nginx/html"
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - webapp
  webapp:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile-dev
      args:
        - COMPOSER_VERSION=${COMPOSER_VERSION}
        - COMPOSER_SUM=${COMPOSER_SUM}
    image: prova-php-entrevista-webapp:dev
    container_name: prova-php-entrevista-webapp
    networks:
      - prova-php-entrevista
    expose:
      - "${WEBAPP_DOCKER_PORT}"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - NODE_ENV=development
